# Generated by Django 4.2.3 on 2023-07-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='admin',
            new_name='adminn',
        ),
    ]
