# Generated by Django 4.2.3 on 2023-07-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_rename_admin_staffs_adminn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='adminn',
            new_name='admin',
        ),
    ]
